---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    users: ["cumulus"]
  tasks:
  - name: push file to sudoers
    template:
      src: ./10-users.j2
      dest: /etc/sudoers.d/10-users
      validate: '/usr/sbin/visudo -cf %s'

